blueprint/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('art/', include('gallery.urls')),
    path('events/', include('events.urls')),
    path('accounts/', include('accounts.urls')),
    path('yourart/', include('yourart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.events, name='events'),
    path('<title>', views.event, name='event'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

events/models.py
from django.db import models
from django.contrib.auth.models import User

from gallery.models import Artist, Artwork


LOC_CHOICES = [
    ('Palace Square, St. Petersburg', 'Palace Square, St. Petersburg'),
    ('Online', 'Online'),
]
ETYPE_CHOICES = [
    ('exhibition', 'Exhibition'),
    ('discussion', 'Discussion'),
    ('workshop', 'Workshop'),
    ('course', 'Course'),
]

class Event(models.Model):
    visitors = models.ManyToManyField(User, blank=True)
    artist = models.ForeignKey(Artist, on_delete=models.SET_NULL, blank=True, null=True)
    artwork = models.ForeignKey(Artwork, on_delete=models.SET_NULL, blank=True, null=True)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100, choices=LOC_CHOICES, default='Palace Square, St. Petersburg')
    etype = models.CharField(max_length=100, choices=ETYPE_CHOICES, default='exhibition')
    start = models.DateTimeField()
    end = models.DateTimeField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    pricem = models.IntegerField(blank=True, null=True)
    descr = models.TextField(max_length=10000, blank=True, null=True)

    class Meta:
        ordering = ['start']

    def __str__(self):
        return self.title

events/forms.py
from django import forms
from .models import LOC_CHOICES, ETYPE_CHOICES

LOC_CHOICES.insert(0, ('all', 'All locations'))

WHEN_CHOICES = [
    ('at', 'All time'),
    ('tw', 'This week'),
    ('nw', 'Next week'),
    ('tm', 'This month'),
    ('nm', 'Next month'),
]

class FilterForm(forms.Form):
    etype = forms.MultipleChoiceField(
        required=False,
        widget=forms.CheckboxSelectMultiple,
        choices=ETYPE_CHOICES,
        label="Event type",
    )
    location = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=LOC_CHOICES,
    )
    when = forms.ChoiceField(
        required=False,
        widget=forms.RadioSelect,
        choices=WHEN_CHOICES,
    )

events/views.py
from datetime import datetime
from datetime import timedelta
from calendar import monthrange

from django.shortcuts import render
from django.db.models import Q

from .models import Event
from .forms import FilterForm


def events(request):
    events = Event.objects.all()
    events_filter = FilterForm(request.GET)
    
    # past events are excluded
    today = datetime.today()
    today = datetime(today.year, today.month, today.day, 23, 59, 59)
    events = events.filter(Q(start__gte=today) | Q(end__gte=today))
    
    etypes = request.GET.get('etypes', '')
    if etypes:
        etypes = etypes.split(',')
        events = events.filter(etype__in=etypes)
    
    location = request.GET.get('location', '')
    if location:
        if location != 'all':
            events = events.filter(location=location)
    
    when = request.GET.get('when', '')
    if when:
        if when == 'tw':
            sooner = today + timedelta(days=6-today.weekday())
            events = events.filter(Q(start__lte=sooner) | Q(end__lte=sooner))
        elif when == 'nw':
            later = today + timedelta(days=6-today.weekday())
            sooner = later + timedelta(days=7)
            events = events.filter(Q(start__gt=later) | Q(end__gt=later),
            Q(start__lte=sooner) | Q(end__lte=sooner))
        elif when == 'tm':
            sooner = datetime(today.year, today.month, monthrange(today.year, today.month)[1])
            events = events.filter(Q(start__lte=sooner) | Q(end__lte=sooner))
        elif when == 'nm':
            later = datetime(today.year, today.month, monthrange(today.year, today.month)[1])
            sooner = later + timedelta(days=monthrange(today.year, today.month+1)[1])
            events = events.filter(Q(start__gt=later) | Q(end__gt=later),
            Q(start__lte=sooner) | Q(end__lte=sooner))
            
    context = {
        'events': events,
        'events_filter': events_filter,
    }
    return render(request, 'events/events.html', context)


def event(request, title):
    event = Event.objects.get(id=title.split('-')[-1])
    return render(request, 'events/event.html', {'ev': event,})

events/templates/events/event.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Event{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'events/styles/event.css' %}" />
{% endblock %}

{% block content %}

<div class="event-wrapper">
    <div class="pic-band">
        <div class="pic-wrapper">
            {% with ev.id|stringformat:"s" as id %}
            {% with ev.title|slugify|add:"-"|add:id as title %}
            <div class="pic">
                {% if not ev.artwork %}
                {% with "events/pics/"|add:title|add:".jpg" as imgref %}
                <img src="{% static imgref %}" />
                {% endwith %}
                {% else %}
                {% with ev.artwork.artist.fname|add:"-"|add:ev.artwork.artist.lname|lower as artist %}
                {% with ev.artwork.title|slugify as artwork %}
                {% with "gallery/pics/"|add:artist|add:"/"|add:artwork|add:".jpg" as imgref %}
                <img src="{% static imgref %}" />
                {% endwith %}
                {% endwith %}
                {% endwith %}
                {% endif %}
            </div>
            {% endwith %}
            {% endwith %}
            <div class="info">
                <h1>{{ ev.title }}</h1>
                <div class="etype">{{ ev.etype }}</div>
                <div class="when">
                    <h4>Dates</h4>
                    <div>
                        {{ ev.start|date:"d M Y" }}{% if ev.end %} - {{ ev.end|date:"d M Y" }}{% endif %}
                    </div>
                </div>
                <div class="pricing">
                    <h4>Pricing</h4>
                    {% if ev.price and ev.pricem %}
                    <div>
                        General public: 
                        <span>{{ ev.price }}</span>
                    </div>
                    <div>
                        Members and patrons: 
                        <span>{{ ev.pricem }}</span>
                    </div>
                    {% else %}
                    <div class="free">free entry</div>
                    {% endif %}
                </div>        
            </div>
        </div>
    </div>

    <div class="details">
        <div class="lorem">
            <h3>Description</h3>
            <p>
                {% lorem 3 p random %}
            </p>
        </div>
        <div class="location">
            {% if ev.location != 'Online' %}
            <figure>
                <figcaption>
                    <h4>Location</h4>
                    <div><a href="#">Plan your visit &rarr;</a></div>
                </figcaption>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1998.6325173245816!2d30.312684215846797!3d59.93823978187607!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4696311064b4ac29%3A0xc1f4a1bc8e98bd91!2sPalace%20Square%2C%20Sankt-Peterburg%2C%20Russia%2C%20191186!5e0!3m2!1sen!2sus!4v1605353937224!5m2!1sen!2sus" width="400" height="300" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
                </iframe>
            </figure>
            {% else %}
            <div class="online">
                <h4>Location</h4>
                <p>This event is <span></span><span>online</span></p>

                <div class="globe">
                    <svg xmlns="http://www.w3.org/2000/svg"
                    version="1.1"
                    x="0px"
                    y="0px"
                    width="32px"
                    height="32px"
                    viewBox="0 0 32 32"
                    enable-background="new 0 0 32 32"
                    xml:space="preserve"
                    id="svg2"
                    inkscape:version="0.48.4 r9939"
                    sodipodi:docname="globe.svg">
                            <defs id="defs3284" />
                            <sodipodi:namedview
                            pagecolor="#ffffff"
                            bordercolor="#666666"
                            borderopacity="1"
                            objecttolerance="10"
                            gridtolerance="10"
                            guidetolerance="10"
                            inkscape:pageopacity="0"
                            inkscape:pageshadow="2"
                            inkscape:window-width="640"
                            inkscape:window-height="480"
                            id="namedview3282"
                            showgrid="false"
                            inkscape:zoom="7.375"
                            inkscape:cx="16"
                            inkscape:cy="16"
                            inkscape:window-x="53"
                            inkscape:window-y="24"
                            inkscape:window-maximized="0"
                            inkscape:current-layer="svg2" />
                            <metadata
                            id="metadata3274"><rdf:RDF><cc:Work
                            rdf:about=""><dc:format>image/svg+xml</dc:format><dc:type
                            rdf:resource="http://purl.org/dc/dcmitype/StillImage" /><dc:title>PICOL Icon</dc:title><dc:date>2009-03-15</dc:date><dc:creator><cc:Agent><dc:title>Melih Bilgil</dc:title></cc:Agent></dc:creator><dc:rights><cc:Agent><dc:title>Creative Commons BY-SA</dc:title></cc:Agent></dc:rights><dc:publisher><cc:Agent><dc:title>PICOL - Pictorial Communication Language</dc:title></cc:Agent></dc:publisher><dc:identifier>http://blog.picol.org</dc:identifier><dc:source>http://blog.picol.org</dc:source><dc:language>en</dc:language><dc:subject><rdf:Bag><rdf:li>PICOL</rdf:li><rdf:li>icon</rdf:li><rdf:li>icons</rdf:li><rdf:li>sign</rdf:li><rdf:li>GUI</rdf:li><rdf:li>vector</rdf:li><rdf:li>interface</rdf:li></rdf:Bag></dc:subject><dc:description>This is one icon out of all PICOL icons</dc:description><dc:contributor><cc:Agent><dc:title>Melih Bilgil (www.lonja.de), Christopher Adjei (www.boffer.net)</dc:title></cc:Agent></dc:contributor><cc:license
                            rdf:resource="http://creativecommons.org/licenses/by-sa/3.0/" /></cc:Work><cc:License
                            rdf:about="http://creativecommons.org/licenses/by-sa/3.0/"><cc:permits
                            rdf:resource="http://creativecommons.org/ns#Reproduction" /><cc:permits
                            rdf:resource="http://creativecommons.org/ns#Distribution" /><cc:requires
                            rdf:resource="http://creativecommons.org/ns#Notice" /><cc:requires
                            rdf:resource="http://creativecommons.org/ns#Attribution" /><cc:permits
                            rdf:resource="http://creativecommons.org/ns#DerivativeWorks" /><cc:requires
                            rdf:resource="http://creativecommons.org/ns#ShareAlike" /></cc:License></rdf:RDF>
                            </metadata>
                            <g id="background"><rect x="0" y="0" fill="none" width="32" height="32" id="rect3277" />
                            </g>
                            <path id="path3280" d="M 15.999,0 C 7.164,0.002 0.002,7.164 0,15.999 0.002,24.837 7.164,31.999 15.999,32 24.837,31.998 31.999,24.837 32,15.999 31.999,7.164 24.837,0.002 15.999,0 z M 2.052,17.001 H 7.04 C 7.111,18.86 7.366,20.528 7.76,22 H 3.373 C 2.642,20.466 2.182,18.783 2.052,17.001 z M 17,8.002 v -5.79 c 0.941,0.705 2.991,2.501 4.433,5.791 H 17 z m 5.169,1.999 c 0.428,1.437 0.714,3.105 0.795,5 H 17 v -5 h 5.169 z M 14.546,2.565 C 14.72,2.421 14.868,2.307 15,2.209 V 8.002 H 10.562 C 11.09,6.799 11.699,5.794 12.305,4.969 13.125,3.855 13.943,3.068 14.546,2.565 z M 15,10.001 v 5 H 9.04 c 0.081,-1.904 0.374,-3.563 0.805,-5 H 15 z m -7.96,5 H 2.052 c 0.129,-1.781 0.588,-3.466 1.319,-5 H 7.76 c -0.394,1.473 -0.649,3.142 -0.72,5 z m 1.995,2 H 15 V 22 H 9.83 C 9.402,20.564 9.116,18.896 9.035,17.001 z m 5.965,7 V 29.79 C 14.06,29.086 12.009,27.291 10.567,24.001 H 15 z m 2.453,5.435 C 17.28,29.58 17.131,29.693 17,29.792 v -5.79 h 4.437 c -0.527,1.202 -1.137,2.206 -1.743,3.031 -0.819,1.112 -1.638,1.901 -2.241,2.403 z M 17,22 v -4.999 h 5.959 C 22.878,18.904 22.585,20.563 22.155,22 H 17 z m 7.96,-4.999 h 4.986 C 29.817,18.782 29.357,20.466 28.626,22 H 24.24 c 0.393,-1.472 0.648,-3.14 0.72,-4.999 z m 0,-2 c -0.072,-1.859 -0.326,-3.527 -0.721,-5 h 4.388 c 0.731,1.534 1.191,3.219 1.319,5 H 24.96 z M 27.473,8.002 H 23.584 C 22.703,5.722 21.547,3.99 20.468,2.747 c 2.864,0.967 5.309,2.827 7.005,5.255 z M 11.531,2.747 C 10.453,3.991 9.296,5.723 8.416,8.002 H 4.527 C 6.224,5.574 8.669,3.714 11.531,2.747 z M 4.53,24.001 h 3.887 c 0.879,2.276 2.034,4.007 3.112,5.25 -2.86,-0.966 -5.303,-2.824 -6.999,-5.25 z m 15.94,5.25 c 1.078,-1.243 2.233,-2.974 3.113,-5.25 h 3.887 c -1.696,2.426 -4.139,4.284 -7,5.25 z" />
                    </svg>
                </div>

            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

events/templates/events/events.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Events{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'events/styles/events.css' %}" />
{% endblock %}

{% block content %}
<div class="content-wrapper">

    <div class="filters-wrapper">
        <form action="{% url 'events:events' %}" method="GET" class="filters">
            {% for filter in events_filter %}
            <fieldset class="filter">
                <legend>{{ filter.label }}</legend>
                {{ filter }}
            </fieldset>
            {% endfor %}
            <input type="hidden" id="etypes" name="etypes" value="">
            <button type="button" class="button">Show results</button>
        </form>
    </div>

    <div class="cards-wrapper">
        <h2>Events</h2>
        <div class="cards">

            {% for ev in events %}
            <div class="card">

                {% with ev.id|stringformat:"s" as id %}
                {% with ev.title|slugify|add:"-"|add:id as title %}

                <div class="card-img">
                    <a href="{% url 'events:event' title %}">
                        {% if not ev.artwork %}
                        {% with "events/pics/"|add:title|add:".thumbnail.jpg" as imgref %}
                        <img src="{% static imgref %}" />
                        {% endwith %}
                        {% else %}
                        {% with ev.artwork.artist.fname|add:"-"|add:ev.artwork.artist.lname|lower as artist %}
                        {% with ev.artwork.title|slugify as artwork %}
                        {% with "gallery/pics/"|add:artist|add:"/"|add:artwork|add:".thumbnail.jpg" as imgref %}
                        <img src="{% static imgref %}" />
                        {% endwith %}
                        {% endwith %}
                        {% endwith %}
                        {% endif %}
                    </a>
                </div>
                <div class="card-content">
                    <span class="card-title">
                        <a href="{% url 'events:event' title %}">
                            {{ ev.title }}
                        </a>
                    </span>
                    <span class="card-location">{{ ev.location }}</span>
                    <span class="card-when">{{ ev.start|date:"d M Y" }}{% if ev.end %} - {{ ev.end|date:"d M Y" }}{% endif %}</span>
                    <span class="card-price">
                        {% if ev.price and ev.pricem %}
                        ticket
                        {% else %}
                        free entry
                        {% endif %}
                    </span>
                </div>

                {% endwith %}
                {% endwith %}

            </div>
            {% endfor %}            
            
        </div>
    </div>

    <script src="{% static 'events/scripts/events.js' %}"></script>
</div>
{% endblock %}