blueprint/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('art/', include('gallery.urls')),
    path('events/', include('events.urls')),
    path('accounts/', include('accounts.urls')),
    path('yourart/', include('yourart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('', views.events, name='events'),
    path('<title>', views.event, name='event'),
]

gallery/urls.py
from django.urls import path

from . import views

app_name = 'gallery'
urlpatterns = [
    path('', views.art, name='art'),
    path('<author>/<work>', views.artwork, name='artwork'),
    path('<author>', views.artist, name='artist'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

gallery/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):
    fname = models.CharField(max_length=30)
    lname = models.CharField(max_length=30)
    born = models.PositiveIntegerField()
    died = models.PositiveIntegerField(blank=True, null=True)
    bio = models.TextField(max_length=10000, blank=True, null=True)
    wiki = models.CharField(max_length=130, blank=True, null=True)

    def __str__(self):
        return "{} {}".format(self.fname, self.lname)


class Artwork(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    ymade = models.PositiveIntegerField()
    medium = models.CharField(max_length=100)
    descr = models.TextField(max_length=10000, blank=True, null=True)

    def __str__(self):
        return self.title

gallery/forms.py
from django import forms

class TestForm(forms.Form):
    your_random_text = forms.CharField(max_length=10)

class SigninForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, max_length=30)

gallery/views.py
from random import sample

from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse, HttpResponseRedirect

from .models import Artist, Artwork
from .forms import TestForm, SigninForm


ARTWORKS_RAND = 8

# Create your views here.
def art(request):
    artworks = [sample(list(el.artwork_set.all()), 1)[0] for el in sample(list(Artist.objects.all()), ARTWORKS_RAND)]
    artists = sorted(Artist.objects.all(), key=lambda artist: artist.lname)
    alphabet = sorted({artist.lname[0] for artist in artists})
    alphabet_artists = [(l,[]) for l in alphabet]
    for l in alphabet_artists:
        for a in artists:
            if a.lname[0] == l[0]:
                l[1].append(a)

    context = {
        'artworks': artworks,
        'alphabet_artists': alphabet_artists,
    }
    return render(request, 'gallery/art.html', context)


def artwork(request, author, work):
    fname, lname = [i.capitalize() for i in author.split('-')]
    artwork_id = int(work.split('-')[-1])
    artist_obj = Artist.objects.get(fname=fname, lname=lname)
    artwork_selected = artist_obj.artwork_set.get(id=artwork_id)
    artwork_list = [i for i in artist_obj.artwork_set.all() if i != artwork_selected]

    context = {
        'artwork_selected': artwork_selected,
        'artwork_list': artwork_list,
    }

    return render(request, 'gallery/artwork.html', context)


def artist(request, author):
    fname, lname = [i.capitalize() for i in author.split('-')]
    artist = Artist.objects.get(fname=fname, lname=lname)
    artwork_list = Artwork.objects.filter(artist=artist)
    try:
        event = artist.event_set.all()[0]
    except:
        event = ''
    context = {
        'artist': artist,
        'artwork_list': artwork_list,
        'ev': event,
    }
    return render(request, 'gallery/artist.html', context)

gallery/templates/gallery/art.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Art{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'gallery/styles/art.css' %}" />
{% endblock %}

{% block content %}
<div class="art-band">
    <div class="art-band-wrapper">
        <div>
            <h2>The Blueprint Collection</h2>
        </div>
        <div>
            <p>Explore the Art and Artists</p>
        </div>
    </div>
</div>
<div class="content-wrapper">

    <div class="artworks-wrapper">
        <h2>Artworks</h2>
        <div class="cards">
            {% include 'card.html' with artworks=artworks %}
        </div>
    </div>

    <div class="artists-wrapper">
        <h2>Artists</h2>
        <div class="artists">
            <ul>
            {% for artists in alphabet_artists %}
            <div class="letter">{{ artists.0 }}</div>
            {% for artist in artists.1 %}
            {% with artist.fname|add:"-"|add:artist.lname|lower as author %}
                <li>
                    <a href="{% url 'gallery:artist' author %}">
                        <span>{{ artist.lname }} {{ artist.fname }}</span>
                    </a>
                </li>
            {% endwith %}
            {% endfor %}

            {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}

gallery/templates/gallery/artist.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Artist{% endblock %}
{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'gallery/styles/artist.css' %}" />
{% endblock %}

{% block content %}
<div class="artist-wrapper">
    <div class="artist-details">
        {% with artist.fname|add:"-"|add:artist.lname|lower as author %}
        <h2>{{ artist.fname }} {{ artist.lname }}</h2>
        <div class="artist-bio">{{ artist.bio|linebreaks }}</div>
        <div class="wiki">
            <a href="https://en.wikipedia.org/wiki/{{ artist.wiki }}">
                <span class="wiki-btn">Read Wikipedia article</span>
            </a>
        </div>
        <div class="artist-pic">
            <figure>
                <img src="{% static '' %}gallery/pics/{{author}}/{{author}}.jpg">
            </figure>

            {% if ev %}
            {% with ev.id|stringformat:"s" as id %}
            {% with ev.title|slugify|add:"-"|add:id as title %}
            <div class="event">
                <div class="card-content">
                    <div class="card-hint">
                        <span></span>
                        <span>see in events</span>
                    </div>
                    <span class="card-title">
                        <a href="{% url 'events:event' title %}">
                            {{ ev.title }}
                        </a>
                    </span>
                    <span class="card-location">{{ ev.location }}</span>
                    <span class="card-when">{{ ev.start|date:"d M Y" }}{% if ev.end %} - {{ ev.end|date:"d M Y" }}{% endif %}</span>
                </div>
            </div>
            {% endwith %}
            {% endwith %}
            {% endif %}
            
        </div>
        {% endwith %}
    </div>
    <div class="artist-artworks">
        <h2>Artworks</h2>
        <div class="artworks">
            {% include 'card.html' with artworks=artwork_list %}
        </div>
    </div>
</div>
{% endblock %}

gallery/templates/gallery/artwork.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Artwork{% endblock %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'gallery/styles/artwork.css' %}" />
{% endblock %}

{% block content %}
<div class="artwork-wrapper">
    
    <h1 class="artwork-title">{{ artwork_selected.title }}</h1>
    <h2 class="artwork-artist">
        {% with artwork_selected.artist.fname|add:"-"|add:artwork_selected.artist.lname|lower as author %}
        <a href="{% url 'gallery:artist' author %}">
            <u>
                {{ artwork_selected.artist.fname }} {{ artwork_selected.artist.lname }}
            </u>
        </a>
        {% endwith %}
    </h2>
    <h2 class="artwork-ymade">{{ artwork_selected.ymade }}</h2>
    <div class="artwork-img-band">
        <figure>
            <div class="artwork-img">
                <img src="{% static '' %}gallery/pics/{{ artwork_selected.artist.fname|lower }}-{{ artwork_selected.artist.lname|lower }}/{{ artwork_selected.title|slugify }}.jpg" />
            </div>
        </figure>

        <div class="lightbox" id="artwork-img-full">
            <div class="lightbox-wrapper">
                <a href="#/" class="close">
                    <span>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.292893 0.292893C0.683417 -0.0976311 1.31658 -0.0976311 1.70711 0.292893L7 5.58579L12.2929 0.292893C12.6834 -0.0976311 13.3166 -0.0976311 13.7071 0.292893C14.0976 0.683417 14.0976 1.31658 13.7071 1.70711L8.41421 7L13.7071 12.2929C14.0976 12.6834 14.0976 13.3166 13.7071 13.7071C13.3166 14.0976 12.6834 14.0976 12.2929 13.7071L7 8.41421L1.70711 13.7071C1.31658 14.0976 0.683417 14.0976 0.292893 13.7071C-0.0976311 13.3166 -0.0976311 12.6834 0.292893 12.2929L5.58579 7L0.292893 1.70711C-0.0976311 1.31658 -0.0976311 0.683417 0.292893 0.292893Z" fill="#0D0D0D"/>
                        </svg>    
                    </span>
                </a>
                <div>
                    <img src="{% static '' %}gallery/pics/{{ artwork_selected.artist.fname|lower }}-{{ artwork_selected.artist.lname|lower }}/{{ artwork_selected.title|slugify }}.jpg"/>
                </div>
            </div>
  
        </div>

        <div class="artwork-img-options-band">
            <div class="artwork-img-options">
                <ul>
                    <li>
                        <a href="#" title="Add to album">
                            <span>
                                <svg width="20" height="16" viewBox="0 0 20 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M0 2C0 0.895432 0.89543 0 2 0H7C7.26522 0 7.51957 0.105357 7.70711 0.292893L9.41421 2H18C19.1046 2 20 2.89543 20 4V14C20 15.1046 19.1046 16 18 16H2C0.895432 16 0 15.1046 0 14V2ZM6.58579 2L2 2V14H18V4H9C8.73478 4 8.48043 3.89464 8.29289 3.70711L6.58579 2ZM10 6C10.5523 6 11 6.44772 11 7V8H12C12.5523 8 13 8.44772 13 9C13 9.55229 12.5523 10 12 10H11V11C11 11.5523 10.5523 12 10 12C9.44771 12 9 11.5523 9 11V10H8C7.44772 10 7 9.55229 7 9C7 8.44772 7.44772 8 8 8H9V7C9 6.44772 9.44771 6 10 6Z" fill="#0D0D0D"/>
                                </svg>                                    
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#artwork-img-full" title="Full screen">
                            <span>
                                <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M2 3.41421V5C2 5.55229 1.55228 6 1 6C0.447715 6 1.78814e-07 5.55229 1.78814e-07 5L0 1C0 0.447716 0.447715 3.57628e-07 1 2.98023e-07L5 0C5.55229 0 6 0.447715 6 1C6 1.55228 5.55229 2 5 2H3.41421L5.70711 4.29289C6.09763 4.68342 6.09763 5.31658 5.70711 5.70711C5.31658 6.09763 4.68342 6.09763 4.29289 5.70711L2 3.41421ZM11 2C10.4477 2 10 1.55229 10 1C10 0.447716 10.4477 1.01328e-06 11 1.01328e-06H15C15.5523 1.01328e-06 16 0.447716 16 1V5.00001C16 5.55229 15.5523 6.00001 15 6.00001C14.4477 6.00001 14 5.55229 14 5.00001V3.41421L11.7071 5.70711C11.3166 6.09763 10.6834 6.09763 10.2929 5.70711C9.90237 5.31658 9.90237 4.68342 10.2929 4.29289L12.5858 2H11ZM1 10C1.55228 10 2 10.4477 2 11L2 12.5858L4.29289 10.2929C4.68342 9.90237 5.31658 9.90237 5.70711 10.2929C6.09763 10.6834 6.09763 11.3166 5.70711 11.7071L3.41421 14H5C5.55228 14 6 14.4477 6 15C6 15.5523 5.55228 16 5 16H1C0.734784 16 0.48043 15.8946 0.292893 15.7071C0.105357 15.5196 0 15.2652 0 15L2.38419e-07 11C2.38419e-07 10.4477 0.447716 10 1 10ZM10.2929 11.7071C9.90237 11.3166 9.90237 10.6834 10.2929 10.2929C10.6834 9.90237 11.3166 9.90237 11.7071 10.2929L14 12.5858V11C14 10.4477 14.4477 10 15 10C15.5523 10 16 10.4477 16 11V15C16 15.5523 15.5523 16 15 16H11C10.4477 16 10 15.5523 10 15C10 14.4477 10.4477 14 11 14H12.5858L10.2929 11.7071Z" fill="#0D0D0D"/>
                                </svg>                                    
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="artwork-details">
        <div class="artwork-details-descr">
            <h3>Description</h3>
            <p class="descr-par">
                {% if artwork_selected.descr %}
                {% autoescape off %}
                {{ artwork_selected.descr|linebreaksbr }}
                {% endautoescape %}
                {% else %}
                <span>None</span>
                {% endif %}
                <div class="par-fadeout"></div>
            </p>
            <button class="descr-btn" type="button">Expand</button>
        </div>
        <div class="artwork-details-info">
            <h3>Artwork</h3>
            <dl>
                <div>
                    <dt>Artist</dt>
                    <dd>
                        {{ artwork_selected.artist.fname }} {{ artwork_selected.artist.lname }} {{ artwork_selected.artist.born }}{% if artwork_selected.artist.died %}-{{ artwork_selected.artist.died }}{% endif %}
                    </dd>    
                </div>
                <div>
                    <dt>Year made</dt>
                    <dd>{{ artwork_selected.ymade }}</dd>    
                </div>
                <div>
                    <dt>Medium</dt>
                    <dd>{{ artwork_selected.medium }}</dd>    
                </div>
            </dl>
        </div>
    </div>

    <div class="artworks-wrapper">
        <div class="artworks-wrapper-clip">
            <div class="artworks" style="transform: translateX(0px);">
                {% include 'card.html' with artworks=artwork_list %}
            </div>
        </div>
        <div class="larr">
            <a>
                <svg width="12" height="24" viewBox="0 0 8 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6 1.5L1 7.5L6 13.5" stroke="#242526" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                </svg>    
            </a>
        </div>
        <div class="rarr">
            <svg width="12" height="24" viewBox="0 0 8 15" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M1.5 13.5L6.5 7.5L1.5 1.5" stroke="#242526" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </div>
    </div>

</div>

<script src="{% static 'gallery/scripts/artwork_gallery.js' %}"></script>
{% endblock %}

gallery/templates/gallery/temp.html
<!DOCTYPE html>
<html>
    <head>
        <title>Temp</title>
    </head>
    <body>
        <div>
            <h2>Ordinary HTML form</h2>
            <form action="temp" method="POST">
                {% csrf_token %}
                <ul>
                    <li>
                        <label for="nickname">Your nickname: </label>
                        <input type="text" id="nickname" name="user_name">
                    </li>
                    <li>
                        <label for="mail">Your email: </label>
                        <input type="email" id="mail" name="user_email">
                    </li>
                    <li>
                        <button type="submit">Send</button>
                    </li>
                </ul>
            </form>
        </div>

        <div>
            <h2>Sign in form</h2>
            <form action="temp" method="POST">
                {% csrf_token %}
                {{ myform }}
                <button type="submit">Sign in</button>
            </form>
        </div>

    </body>
</html>