blueprint/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('art/', include('gallery.urls')),
    path('events/', include('events.urls')),
    path('accounts/', include('accounts.urls')),
    path('yourart/', include('yourart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

yourart/urls.py
from django.urls import path

from . import views

app_name = 'yourart'
urlpatterns = [
    path('', views.yourart, name='yourart'),
    path('<artwork>', views.artwork, name='artwork'),
    path('submit/', views.submit, name='submit'),
]

yourart/models.py
import os

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
def user_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    name = '-'.join(instance.title.strip().lower().replace("'","").split(' '))
    filename = name + ext
    return 'yourart/user_{0}/{1}'.format(instance.user.id, filename)

class Yourart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to=user_path)

    def __str__(self):
        return self.title


class Comment(models.Model):
    artwork = models.ForeignKey(Yourart, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time = models.DateTimeField()
    likes = models.IntegerField(default=0)
    content = models.CharField(max_length=280)

    class Meta:
        ordering = ['-time']

    def __str__(self):
        return self.content

yourart/forms.py
from django import forms
from .models import Yourart

class YourartForm(forms.ModelForm):
    class Meta:
        model = Yourart
        fields = ['user' ,'title', 'image']
        widgets = {'user': forms.HiddenInput}

# class CommentForm(forms.Form):
#     content = forms.CharField(max_length=280,
#     widget=forms.Textarea(attrs={'placeholder': 'Add a comment...'})
#     )

yourart/views.py
import os
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse

from .models import Yourart, Comment
from .forms import YourartForm

# Create your views here.
def yourart(request):
    qs = Yourart.objects.all()
    return render(request, 'yourart/yourart.html', {'qs': qs})


def artwork(request, artwork):
    artwork_id = int(artwork.split('-')[-1])
    artwork = Yourart.objects.get(id=artwork_id)
    user = request.user
    if request.method == 'POST' and len(request.POST['content']) <= 280 and request.user.is_authenticated:
        comment = Comment(
            artwork=artwork,
            user=user,
            time=datetime.now(),
            content=request.POST['content'],
        )
        comment.save()
    
    comments = Comment.objects.all()
    context = {
        'artwork': artwork,
        'comments': comments,
    }
    return render(request, 'yourart/artwork.html', context)



def submit(request):
    if request.method == 'POST' and request.user.is_authenticated:
        data = request.POST.copy()
        data['user'] = request.user
        form = YourartForm(data, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/yourart/')
    elif request.method == 'GET':
        form = YourartForm()
    return render(request, 'yourart/submit.html', {'form': form})

yourart/templates/yourart/artwork.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'yourart/styles/artwork.css' %}" />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
        <title>{{ artwork.title }}</title>
    </head>
    <body>
        <span id="user" hidden>{{ request.user.username }}</span>
        <div class="content-wrapper">
            <div class="content">

                <a href="{% url 'yourart:yourart' %}" class="close">
                    <span>
                        <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M0.292893 0.292893C0.683417 -0.0976311 1.31658 -0.0976311 1.70711 0.292893L7 5.58579L12.2929 0.292893C12.6834 -0.0976311 13.3166 -0.0976311 13.7071 0.292893C14.0976 0.683417 14.0976 1.31658 13.7071 1.70711L8.41421 7L13.7071 12.2929C14.0976 12.6834 14.0976 13.3166 13.7071 13.7071C13.3166 14.0976 12.6834 14.0976 12.2929 13.7071L7 8.41421L1.70711 13.7071C1.31658 14.0976 0.683417 14.0976 0.292893 13.7071C-0.0976311 13.3166 -0.0976311 12.6834 0.292893 12.2929L5.58579 7L0.292893 1.70711C-0.0976311 1.31658 -0.0976311 0.683417 0.292893 0.292893Z" fill="white"/>
                        </svg>    
                    </span>
                </a>

                <div class="image-wrapper">
                    <img src="{{ artwork.image.url }}" />
                </div>

                <div class="sidebar">
                    <div class="info">
                        <h2>{{ artwork.title }}</h2>
                        <div>
                            <span>author: </span>
                            <span>
                                <a href="">{{ artwork.user.username }}</a>
                            </span>
                        </div>
                    </div>
                    <div class="form">
                        <div class="comment-avatar">
                            {% if request.user.account.image %}
                            <img src="{{ request.user.account.image.url }}" />
                            {% else %}
                            <svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M20.418 40.8203C31.3164 40.8203 40.3398 31.7773 40.3398 20.8984C40.3398 10 31.2969 0.976562 20.3984 0.976562C9.51953 0.976562 0.496094 10 0.496094 20.8984C0.496094 31.7773 9.53906 40.8203 20.418 40.8203ZM20.418 27.5586C14.5586 27.5586 10.0273 29.6484 8.05469 31.9922C5.41797 29.0625 3.83594 25.1758 3.83594 20.8984C3.83594 11.6797 11.1797 4.29688 20.3984 4.29688C29.6172 4.29688 37 11.6797 37.0195 20.8984C37.0391 25.1758 35.4375 29.0625 32.8008 32.0117C30.8281 29.668 26.2969 27.5586 20.418 27.5586ZM20.418 24.2383C24.168 24.2773 27.1172 21.0742 27.1172 16.875C27.1172 12.9297 24.168 9.64844 20.418 9.64844C16.668 9.64844 13.6992 12.9297 13.7188 16.875C13.7383 21.0742 16.668 24.1992 20.418 24.2383Z" fill="#999"/>
                            </svg>
                            {% endif %}
                        </div>
                        {% with artwork.id|stringformat:"s" as ids %}
                        {% with artwork.title|slugify|add:"-"|add:ids as work %}        
                        <form id="form" action="{% url 'yourart:artwork' work %}" method="POST">
                            {% csrf_token %}
                            <div class="input">
                                <div id="divtxt" role="textbox" contenteditable="true" aria-multiline="true"></div>
                                <input id="inptxt" type="hidden" name="content" value="">
                            </div>
                            <div class="submit">
                                <button id="cancel" type="button">Cancel</button>
                                <button id="submit" type="submit" form="form" disabled>Submit</button>
                            </div>
                        </form>
                        {% endwith %}
                        {% endwith %}
                    </div>
                    <div class="comments">
                        {% for comment in comments %}
                        {% if comment.artwork == artwork %}
                        <div class="comment">
                            <div class="comment-avatar">
                                {% if comment.user.account.image %}
                                <img src="{{ comment.user.account.image.url }}" />
                                {% else %}
                                <svg width="41" height="41" viewBox="0 0 41 41" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M20.418 40.8203C31.3164 40.8203 40.3398 31.7773 40.3398 20.8984C40.3398 10 31.2969 0.976562 20.3984 0.976562C9.51953 0.976562 0.496094 10 0.496094 20.8984C0.496094 31.7773 9.53906 40.8203 20.418 40.8203ZM20.418 27.5586C14.5586 27.5586 10.0273 29.6484 8.05469 31.9922C5.41797 29.0625 3.83594 25.1758 3.83594 20.8984C3.83594 11.6797 11.1797 4.29688 20.3984 4.29688C29.6172 4.29688 37 11.6797 37.0195 20.8984C37.0391 25.1758 35.4375 29.0625 32.8008 32.0117C30.8281 29.668 26.2969 27.5586 20.418 27.5586ZM20.418 24.2383C24.168 24.2773 27.1172 21.0742 27.1172 16.875C27.1172 12.9297 24.168 9.64844 20.418 9.64844C16.668 9.64844 13.6992 12.9297 13.7188 16.875C13.7383 21.0742 16.668 24.1992 20.418 24.2383Z" fill="#999"/>
                                </svg>
                                {% endif %}
                            </div>
                            <div class="comment-user">
                                <span class="username">
                                    <strong>
                                        <a href="">{{ comment.user.username }}</a>
                                    </strong>
                                </span>
                                <span class="timestamp">{{ comment.time|naturaltime }}</span>
                            </div>
                            <div class="comment-text">
                                <span>{{ comment.content }}</span>
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>            
                </div>

            </div>
        </div>

        <script src="{% static 'yourart/scripts/artwork_yourart.js' %}"></script>
    </body>
</html>

yourart/templates/yourart/submit.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'yourart/styles/submit.css' %}" />
{% endblock %}

{% block content %}

<div class="content-wrapper">

    {% if request.user.is_authenticated %}
    <h3>Upload your artwork</h3>
    <form action="{% url 'yourart:submit' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <ul>
            {{ form.as_ul }}
            <li>
                <button type="submit">Submit</button>
            </li>
        </ul>
    </form>
    {% else %}
    <p class="notification">Please sign in before submitting your work</p>
    {% endif %}
    
</div>

{% endblock %}

yourart/templates/yourart/yourart.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'yourart/styles/yourart.css' %}" />
{% endblock %}

{% block content %}

<div class="submit-band">
    <div class="submit-wrapper">
        <div>
            <h2>Share your artwork with the World</h2>
        </div>
        <div>
            <p>
                Whether you're an apiring artist, art student or just somebody who loves to draw for recreation, just upload your work to Blueprint and let the world see it!
            </p>    
        </div>
        <div> 
            <span class="submit-btn">
                <a href="{% url 'yourart:submit' %}">
                    Upload
                </a>
            </span>
        </div>
    </div>
</div>

<div class="content-band">
    <div class="content-wrapper">

        <div class="pics">
            {% for entry in qs %}

            {% with entry.id|stringformat:"s" as ids %}
            {% with entry.title|slugify|add:"-"|add:ids as work %}
            <div class="pic">
                <div class="pic-img">
                    <a href="{% url 'yourart:artwork' work %}">
                        <img src="{{ entry.image.url }}"/>
                    </a>
                </div>
                <div class="pic-content">
                    <div class="content-artwork">
                        <a href="{% url 'yourart:artwork' work %}">
                            {{ entry.title }}
                        </a>
                        {% if entry.comment_set.all|length %}
                        <span class="comments">
                            <svg width="20" height="18" viewBox="0 0 20 18" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M0 2C0 0.89543 0.895431 0 2 0H18C19.1046 0 20 0.89543 20 2V13C20 14.1046 19.1046 15 18 15H13.4142L10.7071 17.7071C10.3166 18.0976 9.68342 18.0976 9.29289 17.7071L6.58579 15H2C0.89543 15 0 14.1046 0 13V2ZM18 2H2V13H7C7.26522 13 7.51957 13.1054 7.70711 13.2929L10 15.5858L12.2929 13.2929C12.4804 13.1054 12.7348 13 13 13H18V2ZM4 5.5C4 4.94772 4.44772 4.5 5 4.5H15C15.5523 4.5 16 4.94772 16 5.5C16 6.05228 15.5523 6.5 15 6.5H5C4.44772 6.5 4 6.05228 4 5.5ZM4 9.5C4 8.94772 4.44772 8.5 5 8.5H11C11.5523 8.5 12 8.94772 12 9.5C12 10.0523 11.5523 10.5 11 10.5H5C4.44772 10.5 4 10.0523 4 9.5Z" fill="#888"/>
                            </svg>
                            <span>{{ entry.comment_set.all|length }}</span>
                        </span>
                        {% endif %}
                    </div>
                    <div class="content-artist">{{ entry.user.username }}</div>
                </div>
            </div>

            {% endwith %}
            {% endwith %}        
            
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}
            <!-- <div class="card">
                <div class="card-img">
                    <a href="{% url 'yourart:artwork' work %}">
                        <img src="{{ entry.image.url }}"/>
                    </a>
                </div>
                <div class="card-content">
                    <span class="card-artist">{{ entry.user.username }}</span>
                    <span class="card-artwork">
                        <a href="{% url 'yourart:artwork' work %}">
                            {{ entry.title }}
                        </a>
                    </span>
                </div>
            </div> -->