accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('activate/<uid>/<token>', views.activate, name='activate'),
    path('<account>', views.account, name='account'),
]

blueprint/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('art/', include('gallery.urls')),
    path('events/', include('events.urls')),
    path('accounts/', include('accounts.urls')),
    path('yourart/', include('yourart.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

accounts/models.py
import os
import io
import json
from PIL import Image

from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from django.core.files.base import ContentFile

from gallery.models import Artwork
from events.models import Event
from yourart.models import Yourart

IMG_HEIGHT = 190
IMG_WIDTH = 190


# Create your models here.
def user_path(instance, filename):
    ext = os.path.splitext(filename)[1]
    name = instance.user.username
    filename = name + ext
    return f'accounts/{filename}'

def resize(instance):
    f = io.BytesIO()
    img = Image.open(instance.image)
    name = os.path.basename(instance.image.url)
    area = tuple([round(i) for i in json.loads(instance.crop_params)])
    img_crop = img.crop(area)
    img_crop = img_crop.convert('RGB')
    img_crop.thumbnail((IMG_HEIGHT, IMG_WIDTH))
    img.close()
    try:
        img_crop.save(f, format='JPEG')
        s = f.getvalue()
        instance.image.delete()
        instance.save()
        instance.image.save(name, ContentFile(s))
        instance.save()
    finally:
        f.close()


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    artworks = models.ManyToManyField(Artwork, blank=True)
    events = models.ManyToManyField(Event, blank=True)
    yourarts = models.ManyToManyField(Yourart, blank=True)
    image = models.ImageField(upload_to=user_path, blank=True, null=True)
    crop = models.BooleanField(default=False)
    crop_params = models.CharField(max_length=200, blank=True, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.crop == True:
            self.crop = False
            resize(self)
            # if self.image and any((self.image.width > IMG_WIDTH, self.image.height > IMG_HEIGHT)):
            #     resize(self.image.open(), self.crop_params)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from .models import Account


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput, max_length=30)

class RegisterForm(forms.ModelForm):
    password_confirmation = forms.CharField(widget=forms.PasswordInput, max_length=30)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'password': forms.PasswordInput,
            'email': forms.EmailInput,
        }
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_confirmation = cleaned_data.get('password_confirmation')

        if password != password_confirmation:
            raise ValidationError("Password confirmation didn't match password, please try again.")


class AccountFormUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name']
    
    def clean(self):
        cleaned_data = super().clean()
        for field in self.Meta.fields:
            if not cleaned_data.get(field):
                del cleaned_data[field]



class AccountFormAccount(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'id': 'image'})
        self.fields['crop_params'].widget.attrs.update({'id': 'crop_params'})

    av_action = forms.CharField(
        max_length=30,
        required=False,
        widget=forms.HiddenInput(attrs={'id': 'av_action'})
        )
    class Meta:
        model = Account
        fields = ['image', 'crop_params']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.http import HttpResponse, HttpResponseRedirect
from django.core.mail import EmailMessage
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.models import User

from accounts.models import Account
from .forms import LoginForm, RegisterForm, AccountFormUser, AccountFormAccount

# token generator instance
tokenGenerator = PasswordResetTokenGenerator()

# Create your views here.
def login(request):
    auth_msg = ''
    if request.method == 'POST':
        uform = LoginForm(request.POST)
        if uform.is_valid():
            user = authenticate(username=uform.cleaned_data['username'], password=uform.cleaned_data['password'])
            if user is not None:
                auth_login(request, user)
                return HttpResponseRedirect('/art/')
            else:
                auth_msg = 'No user match for username and password provided. Please try again.'
    elif request.method == 'GET':
        uform = LoginForm()
    return render(request, 'accounts/logreg.html', {
        'uform': uform,
        'type': 'login',
        'auth_msg': auth_msg,
        })

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/art/')

def register(request):
    user_created = False
    if request.method == 'POST':
        uform = RegisterForm(request.POST)
        if uform.is_valid():
            user = uform.save(commit=False)
            user.set_password(uform.cleaned_data['password'])
            user.is_active = False
            user.save()
            # create account for the user
            account = Account(user=user)
            account.save()
            email_conf(user)
            user_created = True
    elif request.method == 'GET':
        uform = RegisterForm()
    return render(request, 'accounts/logreg.html', {
        'uform': uform,
        'type': 'register',
        'user_created': user_created,
        })

def email_conf(user):
    token = tokenGenerator.make_token(user)
    username = user.username
    uid = urlsafe_base64_encode(force_bytes(user.id))
    msg = EmailMessage(
        subject='email confirmation',
        body=f'<p>Hello, to activate your account <strong>{username}</strong> please follow the link: <a href="http://127.0.0.1:8000/accounts/activate/{uid}/{token}">Activate<a></p>',
        to=[user.email]
    )
    msg.content_subtype = 'html'
    msg.send()

def activate(request, uid, token):
    try:
        uid_clean = force_str(urlsafe_base64_decode(uid))
        user = User.objects.get(pk=uid_clean)
    except:
        user = None
    check_result = tokenGenerator.check_token(user, token)
    if user is not None and check_result:
        user.is_active = True
        user.save()
        # ! replace automatical logging in with 'success' notification !
        auth_login(request, user)
        return HttpResponseRedirect('/art/')
    else:
        return HttpResponse('Something went wrong.')


def account(request, account):
    user = User.objects.get(id=account.split('-')[1])
    user_account = user.account

    if request.method == 'POST' and request.user.is_authenticated:
        if request.POST['av_action']:
            if request.POST['av_action'] == 'delete':
                user_account.image.delete()
                user_account.crop_params = ''
                user_account.save()
                return HttpResponseRedirect(request.path_info)

            elif request.POST['av_action'] == 'replace':
                user_account.image.delete()
                user_account.crop_params = ''
                user_account.save()
        
        img = user_account.image
        uform = AccountFormUser(request.POST, instance=user)
        aform = AccountFormAccount(request.POST, request.FILES, instance=user_account)
        if uform.is_bound and uform.is_valid():
            uform.save()
        if aform.is_bound and aform.is_valid() and request.POST['av_action']:
            if img:
                user_account.crop = True
                user_account.save()
            aform.save()
        return HttpResponseRedirect(request.path_info)

    uform = AccountFormUser(label_suffix="")
    aform = AccountFormAccount(label_suffix="")
    context = {
        'uform':uform,
        'aform':aform,
    }
    return render(request, 'accounts/account.html', context)

accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/styles/account.css' %}" />
{% endblock %}

{% block content %}
<div class="info-wrapper">

    <div class="info-personal">
        <form action="/accounts/{{ request.user.username }}-{{ request.user.id }}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <ul>
    
                <li>
                    <div class="avatar-title">Profile image</div>
                    <div class="avatar-wrapper">
                        <div>
                            {% if request.user.account.image %}
                            <div class="avatar">
                                <div id="delete">
                                    <div title="delete">
                                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M5 2C5 0.89543 5.89543 0 7 0H13C14.1046 0 15 0.895431 15 2V4H16.9897C16.9959 3.99994 17.0021 3.99994 17.0083 4H19C19.5523 4 20 4.44772 20 5C20 5.55228 19.5523 6 19 6H17.9311L17.0638 18.1425C16.989 19.1891 16.1182 20 15.0689 20H4.93112C3.88184 20 3.01096 19.1891 2.9362 18.1425L2.06888 6H1C0.447715 6 0 5.55228 0 5C0 4.44772 0.447715 4 1 4H2.99174C2.99795 3.99994 3.00414 3.99994 3.01032 4H5V2ZM7 4H13V2H7V4ZM4.07398 6L4.93112 18H15.0689L15.926 6H4.07398ZM8 8C8.55228 8 9 8.44772 9 9V15C9 15.5523 8.55228 16 8 16C7.44772 16 7 15.5523 7 15V9C7 8.44772 7.44772 8 8 8ZM12 8C12.5523 8 13 8.44772 13 9V15C13 15.5523 12.5523 16 12 16C11.4477 16 11 15.5523 11 15V9C11 8.44772 11.4477 8 12 8Z" fill="#999"/>
                                        </svg>                                            
                                    </div>
                                </div>
                                {% if not request.user.account.crop_params %}
                                <div id="area">
                                </div>
                                {% endif %}
                                <img id="avatar" src="{{ request.user.account.image.url }}" />
                                {{ aform.crop_params }}
                            </div>
                            {% else %}
                            <div>
                                <div class="square">
                                    <span>Images must be .png or .jpg format</span>
                                </div>
                            </div>
                            {% endif %}
                            <div class="avatar-btn">
                                {{ aform.image }}
                                {{ aform.av_action }}
                                <button type="button" id="avatar-btn">Select</button>
                            </div>
                        </div>
                    </div>

                </li>
    
                <li>
                    <div class="username">{{ request.user.username }}</div>
                    <div class="joined">Member since {{ request.user.date_joined|date:"M Y" }}</div>
                    <div class="email">{{ request.user.email }}</div>
                </li>
    



                <li>
                    <div class="data-db fname">
                        <div>
                            <span>First name</span>
                            <span class="edit"><button type="button" id="fname-edit"><u>Edit</u></button></span>
                        </div>
                        <div>{{ request.user.first_name }}</div>
                    </div>
                    <div class="data-form fname">
                        {{ uform.first_name.label_tag }}
                        {{ uform.first_name }}
                        <div class="submit-wrapper">
                            <button type="submit" class="submit" id="save-fname" disabled>Save</button>    
                            <button type="button" class="cancel fname"><u>Cancel</u></button>
                        </div>
                    </div>
                </li>
    
                <li>
                    <div class="data-db lname">
                        <div>
                            <span>Last name</span>
                            <span class="edit"><button type="button" id="lname-edit"><u>Edit</u></button></span>
                        </div>
                        <div>{{ request.user.last_name }}</div>
                    </div>
                    <div class="data-form lname">
                        {{ uform.last_name.label_tag }}
                        {{ uform.last_name }}
                        <div class="submit-wrapper">
                            <button type="submit" class="submit" id="save-lname">Save</button>    
                            <button type="button" class="cancel lname"><u>Cancel</u></button>
                        </div>
                    </div>
                </li>
    
                <li></li>
            </ul>
        </form>
    
    </div>

    <div class="info-site"></div>


    <script src="{% static 'accounts/scripts/account.js' %}"></script>
</div>

{% endblock %}

accounts/templates/accounts/logreg.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/styles/logreg.css' %}" />
{% endblock %}

{% block content %}

<div class="content-wrapper">

    {% if type == "login" %}
    <div class="link-reg">First time here? <a href="{% url 'accounts:register' %}">Create an Account</a></div>
    <h3>Sign in</h3>
    <form action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        <ul>
            {% if auth_msg %}
            <li>
                {{ auth_msg }}
            </li>
            {% endif %}
            {% for field in uform.visible_fields %}
            <li>
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </li>
            {% endfor %}
            <li>
                <button type="submit">Sign in</button>
            </li>
        </ul>
    </form>

    {% elif type == "register" %}
    {% if not user_created %}
    <div class="link-signin">Already have a Blueprint account? <a href="{% url 'accounts:login' %}">Sign in</a></div>
    <h3>Register</h3>
    <form action="{% url 'accounts:register' %}" method="post">
        {% csrf_token %}
        <ul>
            <li>
                {{ uform.non_field_errors }}
            </li>
            {% for field in uform.visible_fields %}
            <li>
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
            </li>
            {% endfor %}
            <li>
                <button type="submit">Register</button>
            </li>
        </ul>
    </form>
    {% elif user_created %}
    <p class="notification">
        Confirmation email has been sent to your email address. Please follow the link in the email to activate your account.
    </p>
    {% endif %}

    {% endif %}
    
</div>

{% endblock %}